"""
build_standalone.py
===================
Packages pdn_sim3.py simulation results into a single self-contained
dashboard_standalone.html (no HTTP server required).

Usage:
    python3 build_standalone.py [--cycles 2000] [--out dashboard_standalone.html]

Workflow:
    1. Runs pdn_sim3.py via run_sim.py to generate sim_results.json
    2. RLE-compresses bool arrays, rounds floats
    3. Inlines JSON as window._SIM_DATA into dashboard.html
    4. Writes dashboard_standalone.html
"""

import json
import argparse
import subprocess
import os
import sys


def rle_encode(lst):
    """Run-length encode a list of booleans -> [[val,count], ...]"""
    if not lst:
        return []
    out = []
    cur = lst[0]
    cnt = 1
    for v in lst[1:]:
        if bool(v) == bool(cur):
            cnt += 1
        else:
            out.append([int(bool(cur)), cnt])
            cur = v
            cnt = 1
    out.append([int(bool(cur)), cnt])
    return out


def slim_results(data: dict) -> dict:
    """Round floats and RLE-encode bool arrays to reduce payload size."""
    for bm_key in data["data"]:
        for mode in ("on", "off"):
            r = data["data"][bm_key][mode]
            r["voltage_mv"] = [round(v, 1) for v in r["voltage_mv"]]
            r["m5_rle"]    = rle_encode(r.pop("m5_lock"))
            r["comp_rle"]  = rle_encode(r.pop("comp_active"))
    data["meta"]["pdn_calib"] = [round(v, 1) for v in data["meta"]["pdn_calib"]]
    return data


INLINE_PREAMBLE = """
/* ── INLINE SIMULATION DATA (generated by build_standalone.py) ── */
(function () {
  function decodeRle(rle, n) {
    const out = new Array(n).fill(false);
    let i = 0;
    for (const [val, cnt] of rle) {
      for (let j = 0; j < cnt; j++) out[i++] = !!val;
    }
    return out;
  }
  const raw = __JSON_PLACEHOLDER__;
  for (const bm of Object.values(raw.data)) {
    for (const r of [bm.on, bm.off]) {
      const n = r.voltage_mv.length;
      r.m5_lock     = decodeRle(r.m5_rle  || [], n);
      r.comp_active = decodeRle(r.comp_rle || [], n);
      delete r.m5_rle;
      delete r.comp_rle;
    }
  }
  window._SIM_DATA = raw;
})();
"""

PATCHED_LOAD_FN = """\
async function loadData() {
  try {
    if (window._SIM_DATA) { SIM = window._SIM_DATA; initUI(); return; }
    const resp = await fetch("sim_results.json");
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    SIM = await resp.json();
    initUI();
  } catch(e) {
    document.getElementById("loading").style.display = "none";
    document.getElementById("error-msg").style.display = "flex";
    console.error(e);
  }
}"""

ORIGINAL_LOAD_FN = """\
async function loadData() {
  try {
    const resp = await fetch("sim_results.json");
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    SIM = await resp.json();
    initUI();
  } catch(e) {
    document.getElementById("loading").style.display = "none";
    const el = document.getElementById("error-msg");
    el.style.display = "flex";
    console.error(e);
  }
}"""


def build(cycles: int, out_path: str, base_dir: str):
    # ── Step 1: run simulation ─────────────────────────────────
    json_path = os.path.join(base_dir, "sim_results.json")
    print(f"[build] Running simulation ({cycles} cycles)...")
    result = subprocess.run(
        [sys.executable, os.path.join(base_dir, "run_sim.py"),
         "--cycles", str(cycles), "--out", "sim_results.json"],
        cwd=base_dir, capture_output=True, text=True
    )
    if result.returncode != 0:
        print(result.stdout); print(result.stderr)
        raise RuntimeError("Simulation failed")
    print(result.stdout.strip())

    # ── Step 2: load & slim JSON ───────────────────────────────
    with open(json_path) as f:
        data = json.load(f)
    data = slim_results(data)
    json_str = json.dumps(data, separators=(",", ":"))
    print(f"[build] Inline JSON size: {len(json_str)/1024:.1f} KB")

    # ── Step 3: read dashboard template ───────────────────────
    dash_path = os.path.join(base_dir, "dashboard.html")
    with open(dash_path) as f:
        html = f.read()

    # ── Step 4: patch loadData ─────────────────────────────────
    if ORIGINAL_LOAD_FN in html:
        html = html.replace(ORIGINAL_LOAD_FN, PATCHED_LOAD_FN)
    else:
        # already patched or different whitespace — just ensure window check exists
        if "window._SIM_DATA" not in html:
            print("[build] WARNING: could not patch loadData exactly; inserting fallback")
            html = html.replace(
                "const resp = await fetch",
                "if (window._SIM_DATA) { SIM = window._SIM_DATA; initUI(); return; }\n    const resp = await fetch"
            )

    # ── Step 5: inject inline data before </head> ─────────────
    inline = f"<script>{INLINE_PREAMBLE.replace('__JSON_PLACEHOLDER__', json_str)}</script>"
    if "</head>" not in html:
        raise RuntimeError("No </head> tag found in dashboard.html")
    html = html.replace("</head>", inline + "\n</head>", 1)

    # ── Step 6: write output ───────────────────────────────────
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    size_kb = os.path.getsize(out_path) / 1024
    print(f"[build] Written → {out_path}  ({size_kb:.1f} KB)")
    print("[build] Done. Open the HTML file directly in any browser.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Build standalone dashboard HTML")
    parser.add_argument("--cycles", type=int, default=2000)
    parser.add_argument("--out", type=str, default="dashboard_standalone.html")
    args = parser.parse_args()

    base = os.path.dirname(os.path.abspath(__file__))
    out  = args.out if os.path.isabs(args.out) else os.path.join(base, args.out)
    build(args.cycles, out, base)
